// react-app/app/src/modules/Admin/ManageSubjects/ModifySubject/ModifySubject.js
import React from 'react';
import { Link } from 'react-router-dom';

import { getSubject, removeSubject, createOrModifySubject } from '../ManageSubjects.services';
import { getStudents } from '../../ManageStudents/ManageStudents.services';

import Admin from '../../Admin';

import { Subject } from './Subject';

class ModifySubject extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			title: '',
			subjectId: '',
			subjectItem: Subject,

			isError: false,
			notify: '',
			isDone: false,

			tab: 'general',

			students: [],
			removedStudents: [],
			addedStudents: [],

			studentKeyword: '',
			searchStudentNotify: ''
		};

		this.createOrModify = this.createOrModify.bind(this);
		this.delete         = this.delete.bind(this);
		this.searchStudents = this.searchStudents.bind(this);
	}

	componentDidMount() {
		this.checkMode();
	}

	checkMode() {
		let subjectId = this.props.match.params.id;

		if(subjectId && !isNaN(Number(subjectId))) {
			this.setState({
				title: 'Edit Subject',
				subjectId
			}, () => {
				this.getSubject();
			});
		} else {
			this.setState({
				subjectItem: Subject,
				title: 'Create Subject'
			});
		}
	}

	changeTab(tab) {
		this.setState({ tab });
	}

	getSubject() {
		getSubject(Number(this.state.subjectId))
			.then(res => {
				this.setState({ subjectItem: res.data }, () => {

					this.getStudents();
				});
			})
			.catch(err => {
				console.log(err);
			});
	}

	getStudents() {
		getStudents({ subject_id: Number(this.state.subjectId) })
			.then(res => {
				this.setState({ students: res.data.students });
			})
			.catch(err => {
				console.log(err);
			});
	}

	removeStudent(id) {
		this.setState((prevState) => {
			let removedStudents = [...prevState.removedStudents];
			let students        = [...prevState.students];

			removedStudents.push(id);
			students = students.filter((s) => {
				return s["_id"] !== id;
			});

			return {
				removedStudents,
				students
			};
		});
	}

	addStudent(student) {
		this.setState((prevState) => {
			let addedStudents = [...prevState.addedStudents];
			let students      = [...prevState.students];

			addedStudents.push(student["_id"]);
			students.push(student);

			return {
				addedStudents,
				students
			};
		});
	}

	searchStudents() {
		if(!this.state.studentKeyword) return;

		this.setState({ searchStudentNotify: '' });

		getStudents({ keyword: this.state.studentKeyword })
			.then(res => {
				if(res.data.count && res.data.count === 1) {
					let isExistStudent = this.state.students.find(s => s["student_number"] === res.data.students[0]["student_number"]);
					if(!isExistStudent) {
						this.addStudent(res.data.students[0]);
					} else {
						this.setState({ searchStudentNotify : 'This student has added before!' });
					}
				} else {
					this.setState({ searchStudentNotify: 'Not found this students!' });
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	createOrModify(isContinue=false) {
		this.notify = "";
		this.isError= false;
		this.isDone = false;

		this.setState({
			notify: '',
			isError: false,
			isDone: false
		});

		this.removeTheSameStudentsBeforeUpdate(() => {

			// console.log(this.state.subjectItem);

			createOrModifySubject(this.state.subjectItem)
				.then(res => {
					// console.log("create or modify subject: ", res.data);
					const resData = res.data;

					if(resData.ok && resData.ok === 1) {

						this.setState({ isDone: true });

						if(!isContinue) {
							this.setState({ subjectItem: Subject }, () => {
								this.props.history.push('/admin/subjects');
							});
						}
					}

					if(resData.err && resData.err === 1) {
						this.setState({
							notify: resData.msg,
							isError: true
						});
					}

				})
				.catch(err => {
					console.log(err);
				});
		});
	}

	removeTheSameStudentsBeforeUpdate(cb) {
		let dupplicatedStudents = this.state.removedStudents.filter((s) => { return this.state.addedStudents.indexOf(s) > -1; });

		let addedStudents = this.state.addedStudents.filter((s) => { return dupplicatedStudents.indexOf(s) === -1; });
		let removedStudents = this.state.removedStudents.filter((s) => { return dupplicatedStudents.indexOf(s) === -1; });

		this.setState((prevState) => {
			let subjectItem = {...prevState.subjectItem};
			subjectItem["removed_students"] = removedStudents;
			subjectItem["added_students"]   = addedStudents;

			return {
				subjectItem,
				removedStudents,
				addedStudents
			};
		}, () => {
			cb();
		});
	}

	delete() {
		let isConfirm = window.confirm("Are you sure delete this subject?");
		if(isConfirm) {
			const { subjectId } = this.state;
			removeSubject(Number(subjectId))
				.then(res => {
					this.props.history.push('/admin/subjects');
				})
				.catch(err => {
					console.log(err);
				});
		}
	}

	render() {
		const { title, subjectId, subjectItem, isError, notify, isDone, students, tab } = this.state;

		let deleteBtn;
		if(subjectId) {
			deleteBtn = <a className="button" onClick={this.delete}>Delete</a>;
		} else {
			deleteBtn = null;
		}

		return (
			<Admin>
				<div className="page">
					<div className="head-content clearfix">
						<h1 className="title">{title}</h1>

						<div className="action">
							{ deleteBtn }
							<a className="button" onClick={() => this.createOrModify()}>Save</a>
							<a className="button" onClick={() => this.createOrModify(true)}>Save And Continue</a>
						</div>
					</div>
					<div className="body-content">
						<form>
							<div className={"notify " + (isError? 'active' : '')}>{notify}</div>
							<div className={"notify success " + (isDone? 'active' : '')}>Saved!</div>

							<ul className="tabs clearfix">
								<li className={tab === 'general' ? 'active': ''} onClick={() => this.changeTab('general')}>General</li>
								<li className={tab === 'students' ? 'active': ''} onClick={() => this.changeTab('students')}>Manage Students</li>

							</ul>

							<div className={'tab-content ' + (tab === 'general'? 'show': '')}>

								<div className="input">
									<label htmlFor="subject_number">
										Subject Number
										<span className="required">*</span>
									</label>
									<input type="text" id="subject_number" name="subject_number" value={subjectItem.subject_number} onChange={(e) => this.onChangeSubjectItem("subject_number", e.target.value)} />
								</div>

								<div className="input">
									<label htmlFor="name">
										Name
										<span className="required">*</span>
									</label>
									<input type="text" id="name" name="name" value={subjectItem.name} onChange={(e) => this.onChangeSubjectItem("name", e.target.value)} />
								</div>								

								<div className="col2">

									{/*Started-End years*/}
									<div className="input">
										<label htmlFor="started_year">
											Started Year
											<span className="required">*</span>
										</label>
										<select value={subjectItem.started_year} onChange={(e) => this.onChangeSubjectItem("started_year", e.target.value)}>
											<option key="snone" value=""></option>
											<option key="s2014" value="2014">2014</option>
											<option key="s2015" value="2015">2015</option>
											<option key="s2016" value="2016">2016</option>
											<option key="s2017" value="2017">2017</option>
											<option key="s2018" value="2018">2018</option>
											<option key="s2019" value="2019">2019</option>
											<option key="s2020" value="2020">2020</option>
											<option key="s2021" value="2021">2021</option>
											<option key="s2022" value="2022">2022</option>
										</select>
									</div>
									<div className="input">
										<label htmlFor="ended_year">
											Ended Year
											<span className="required">*</span>
										</label>
										<select value={subjectItem.ended_year} onChange={(e) => this.onChangeSubjectItem("ended_year", e.target.value)}>
											<option key="enone" value=""></option>
											<option key="e2014" value="2014">2014</option>
											<option key="e2015" value="2015">2015</option>
											<option key="e2016" value="2016">2016</option>
											<option key="e2017" value="2017">2017</option>
											<option key="e2018" value="2018">2018</option>
											<option key="e2019" value="2019">2019</option>
											<option key="e2020" value="2020">2020</option>
											<option key="e2021" value="2021">2021</option>
											<option key="e2022" value="2022">2022</option>
										</select>
									</div>

								</div>

								<div className="input">
									<label htmlFor="description">
										Description
									</label>
									<input type="text" id="description" name="description" value={subjectItem.description} onChange={(e) => this.onChangeSubjectItem("description", e.target.value)} />
								</div>

								<div className="input">
									<label htmlFor="status">
										Status
										<span className="required">*</span>
									</label>
									<select onChange={(e) => this.onChangeSubjectItem("status", e.target.value)}>
										<option value="enabled">Enabled</option>
										<option value="disabled">Disabled</option>
									</select>
								</div>

							</div>

							<div className={'tab-content ' + (tab === 'students'? 'show': '')}>

								{ this.state.searchStudentNotify !== '' ? 
									<p style={{fontSize: '13px', color: '#222'}}>{this.state.searchStudentNotify}</p> : null }

								<div className="search clearfix" style={{marginBottom: '25px'}}>
									<input type="text" name="search-input" id="search-input" placeholder="Enter Student Number" value={this.state.studentKeyword} onChange={(e) => {
										this.setState({ studentKeyword: e.target.value });
									}} />
									<button style={{padding: '8px 15px 9px 15px', fontSize: '14px', textTransform: 'capitalize', backgroundColor: '#6d7d85'}} onClick={this.searchStudents}>Add Student</button>
								</div>

								<p style={{marginBottom: '3px'}}>
									<strong style={{fontWeight: 500}}>List students</strong>
								</p>

								<ul className="list-checkbox students">

									{ students.map((item, index) => (
										<li key={index}>
											<label className="container">
												<Link to={'/admin/students/edit/' + item._id} style={{color: 'var(--text)'}} title={item.student_number}>
													<span className="student-number">{item.student_number}</span>
													<span className="student-name">{item.first_name} {item.last_name}</span>
												</Link>
												<input type="checkbox" name={item._id} checked={true} onChange={() => this.removeStudent(item._id)} />
												<span className="checkmark"></span>
											</label>
										</li>
									)) }

								</ul>

							</div>

						</form>
					</div>
				</div>
			</Admin>
		);
	}

	onChangeTeacherItem(key, value) {
		this.setState(prevState => {
			let teacherItem = {...prevState.teacherItem};

			teacherItem[key] = value;

			return {
				teacherItem
			};
		});
	}
}; 

export default ModifySubject;

// app/src/app/modules/Admin/ManageSubjects/ModifySubject/ModifySubject.component.ts
import { Component, OnInit, OnChanges } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

import { SubjectService } from '../ManageSubjects.service';
import { StudentService } from '../../ManageStudents/ManageStudents.service';

@Component({
	selector: 'modify-subject',
	templateUrl: './ModifySubject.component.html',
	styleUrls: ['./ModifySubject.component.css']
})

export class ModifySubjectComponent implements OnInit, OnChanges {
	title    : string;
	subjectId  : string;
	subjectItem: Object = {};
	isError  : boolean = false;
	notify   : string;
	isDone   : boolean = false;
	tab      : string='general';
	students : Object[] = [];
	removedStudents: Object[] = [];
	addedStudents  : Object[] = [];

	studentKeyword: string;
	searchStudentNotify: string="";

	constructor(
		private subjectService: SubjectService,
		private studentService: StudentService,
		private activatedRoute: ActivatedRoute,
		private router: Router) {
		
	}

	ngOnInit() {
		this.checkMode();
	}

	ngOnChanges() {
		this.checkMode();
	}

	changeTab(tab:string='general') {
		this.tab = tab;
	}

	checkMode() {
		this.subjectId = this.activatedRoute.snapshot.paramMap.get('id');
		// console.log(this.subjectId);

		if(this.subjectId && !isNaN(Number(this.subjectId))) {
			this.title = "Edit Subject";
			this.getSubject();
		} else {
			this.subjectItem = {};
			this.title = "Create Subject";
		}
	}

	getSubject() {
		this.subjectService.get(Number(this.subjectId))
			.then(resData => {
				// console.log("subject: ", resData);
				if(resData) {
					this.subjectItem = resData;

					this.getStudents();
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	getStudents() {
		this.studentService.getAll({ subject_id: this.subjectItem["_id"] })
			.then(resData => {
				this.students = resData.students;
				// console.log(this.students);
			})
			.catch(err => {
				console.log(err);
			});
	}

	removeStudent(id: number){
		this.removedStudents.push(id);
		this.students = this.students.filter((s) => {
			return s["_id"] != id;
		});
	}

	searchStudents() {
		if(!this.studentKeyword) return;

		this.searchStudentNotify = "";

		this.studentService.getAll({ keyword: this.studentKeyword })
			.then(resData => {
				// console.log(resData);
				if(resData.count && resData.count === 1) {
					let isExistStudent = this.students.find(s => s["student_number"] == resData.students[0]["student_number"]);
					if(!isExistStudent) {

						this.addedStudents.push(resData.students[0]["_id"]);
						this.students.push(resData.students[0]);
					} else {
						this.searchStudentNotify = "This student has added before!";
					}
				} else {
					this.searchStudentNotify = "Not found this student!";
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	createOrModify(isContinue: boolean=false) {
		this.notify = "";
		this.isError= false;
		this.isDone = false;

		this.removeTheSameStudentsBeforeUpdate();

		this.subjectItem["removed_students"] = this.removedStudents;
		this.subjectItem["added_students"]   = this.addedStudents;
		// console.log(this.subjectItem);

		this.subjectService.createOrModify(this.subjectItem)
			.then(resData => {
				// console.log("create or modify subject: ", resData);

				if(resData.ok && resData.ok === 1) {
					this.isDone = true;
					if(!isContinue) {
						this.subjectItem = {};
						this.router.navigate(['admin/subjects']);
					}
				}

				if(resData.err && resData.err === 1) {
					this.notify = resData.msg;
					this.isError= true;
				}

			})
			.catch(err => {
				console.log(err);
			});
	}

	removeTheSameStudentsBeforeUpdate() {
		let dupplicateStudents = this.removedStudents.filter((v) => { return this.addedStudents.indexOf(v) > -1; });
		// console.log("dupplicateStudents: ", dupplicateStudents);

		this.addedStudents     = this.addedStudents.filter((v) => { return dupplicateStudents.indexOf(v) == -1; });
		this.removedStudents   = this.removedStudents.filter((v) => { return dupplicateStudents.indexOf(v) == -1; });
	}

	delete() {
		let isConfirm = confirm("Are you sure delete this subject?");
        if(isConfirm){
            this.subjectService.remove(Number(this.subjectId))
            	.then(resData => {
            		// console.log(resData);
            		this.router.navigate(['admin/subjects']);
            	})
            	.catch(err => {
            		console.log(err);
            	});
        }
	}
}
<div class="page">
	<div class="head-content clearfix">
		<h1 class="title">{{title}}</h1>

		<div class="action">
			<a class="button" *ngIf="subjectId" (click)="delete()">Delete</a>
			<a class="button" (click)="createOrModify()">Save</a>
			<a class="button" (click)="createOrModify(true)">Save And Continue</a>
		</div>
	</div>
	<div class="body-content">

		<form>
			
			<div class="notify" [ngClass]="{ 'active': isError }">{{notify}}</div>
			<div class="notify success" [ngClass]="{'active': isDone}">Saved!</div>

			<ul class="tabs clearfix">
				<li [ngClass]="{'active': tab === 'general'}" (click)="changeTab('general')">General</li>
				<li [ngClass]="{'active': tab === 'students'}" (click)="changeTab('students')">Manage Students</li>
			</ul>

			<div class="tab-content" [ngClass]="{'show': tab === 'general'}">
				<div class="input">
					<label for="subject_number">
						Subject Number
						<span class="required">*</span>
					</label>
					<input type="text" id="subject_number" name="subject_number" [(ngModel)]="subjectItem.subject_number">
				</div>

				<div class="input">
					<label for="name">
						Name
						<span class="required">*</span>
					</label>
					<input type="text" id="name" name="name" [(ngModel)]="subjectItem.name">
				</div>

				<div class="col2">
					<div class="input">
						<label for="started_year">
							Started Year
							<span class="required">*</span>
						</label>
						<select [(ngModel)]="subjectItem.started_year" [ngModelOptions]="{standalone: true}">
							<option value="2014">2014</option>
							<option value="2015">2015</option>
							<option value="2016">2016</option>
							<option value="2017">2017</option>
							<option value="2018">2018</option>
							<option value="2019">2019</option>
							<option value="2020">2020</option>
							<option value="2021">2021</option>
							<option value="2022">2022</option>
						</select>
					</div>
					<div class="input">
						<label for="ended_year">
							Ended Year
							<span class="required">*</span>
						</label>
						<select [(ngModel)]="subjectItem.ended_year" [ngModelOptions]="{standalone: true}">
							<option value="2014">2014</option>
							<option value="2015">2015</option>
							<option value="2016">2016</option>
							<option value="2017">2017</option>
							<option value="2018">2018</option>
							<option value="2019">2019</option>
							<option value="2020">2020</option>
							<option value="2021">2021</option>
							<option value="2022">2022</option>
						</select>
					</div>
				</div>

				<div class="input">
					<label for="description">
						Description
					</label>
					<textarea rows="5" id="description" name="description" [(ngModel)]="subjectItem.description"></textarea>
				</div>

				<div class="input">
					<label for="status">
						Status
						<span class="required">*</span>
					</label>
					<select [(ngModel)]="subjectItem.status" [ngModelOptions]="{standalone: true}">
						<option value="enabled">Enabled</option>
						<option value="disabled">Disabled</option>
					</select>
				</div>
			</div>

			<div class="tab-content" [ngClass]="{'show': tab === 'students'}">
				<p *ngIf="searchStudentNotify" style="font-size: 13px; color: #222;">{{searchStudentNotify}}</p>
				<div class="search clearfix" style="margin-bottom: 25px;">
					<input type="text" name="search-input" id="search-input" [(ngModel)]="studentKeyword" placeholder="Enter Student number" (keydown.enter)="searchStudents()">
					<button (click)="searchStudents()" style="padding: 9px 15px; font-size: 13px; text-transform: capitalize; background-color: #6d7d85;">Add Student</button>
				</div>

				<p style="margin-bottom: 3px;">
					<strong style="font-weight: 500;">List students</strong>
				</p>
				<ul class="list-checkbox students">
					<li *ngFor="let student of students">
						<label class="container">
							<a [routerLink]="['/admin/students', 'edit', student._id]" style="color: var(--text);" [title]="student.student_number">
								<span class="student-number">{{student.student_number}}</span>
								<span class="student-name">{{student.first_name}} {{student.last_name}}</span>
							</a>
							<!-- <a [routerLink]="['/admin/students', 'edit', student._id]">View</a> -->
							<input type="checkbox" [name]="student._id" checked="true" (change)="removeStudent(student._id)" value="student._id">
							<span class="checkmark"></span>
						</label>
					</li>
				</ul>
			</div>

		</form>
	</div>
</div>
