// react-app/app/src/modules/Admin/ManageStudents/ManageStudents/ManageStudents.js
import React from 'react';
import { Link } from 'react-router-dom';

import { getStudents } from '../ManageStudent.services';
import { getClasses }  from '../../ManageClasses/ManageClasses.services';
import { getSubjects } from '../../ManageSubjects/ManageSubjects.services';

import { myDateFormat } from '../../../Utils/DateFormat';

import Admin from '../../Admin';

class ManageStudents extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			students: [],
			count: 0,
			classes: [],
			subjects: [],

			skip: "0",
			limit: "10",
			pages: 0,
			pagers: [],
			classId: 'all',
			subjectId: 'all',
			keyword: null
		};
	}

	componentDidMount() {
		this.getClasses();
		this.getSubjects();

		// First load
		this.getStudents();
	}

	getClasses() {
		getClasses()
			.then(res => {
				this.setState({ classes: res.data.classes });
			})
			.catch(err => {
				console.log(err);
			});
	}

	getSubjects() {
		getSubjects()
			.then(res => {
				this.setState({ subjects: res.data.subjects });
			})
			.catch(err => {
				console.log(err);
			});
	}

	getStudents(page=0) {
		const { limit, classId, subjectId, keyword } = this.state;

		getStudents({
			skip      : page,
			limit,
			class_id  : classId,
			subject_id: subjectId,
			keyword
		})
		.then(res => {
			let resData = res.data;

			console.log("students: ", resData);

			this.setState({ 
				students: resData.students,
				count   : resData.count,
				skip    : (Number(resData.skip) + 1).toString(),
				limit   : resData.limit,
				pages   : (Number(resData.limit) !== 0) ? Math.ceil(Number(resData.count) / Number(resData.limit)) : 0
			}, () => {
				this.initPagers();
			});
		})
		.catch(err => {
			console.log(err);
		});
	}

	initPagers() {
		let pagers = [];
		for(let i = 1; i <= this.state.pages; i++){
			pagers.push(i);
		}

		this.setState({ pagers });
	}

	viewPage(skip=0) {
		let skipPage = Number(skip) > 0 ? Number(skip) - 1 : 0;
		this.getStudents(skipPage);
	}

	render() {
		const { students, count, classes, subjects } = this.state;

		return (
			<Admin>
				<div className="page">

					<div className="head-content clearfix">
						<h1 className="title">Management Students</h1>
						<div className="action">
							<Link className="button" to="/admin/students/create">+ Add Student</Link>
						</div>
					</div>

					<div className="body-content">

						{/* Toolbar */}
						<div className="toolbar clearfix">
							<div className="filter clearfix">
								<select className="classes" onChange={(e) => {
									this.setState({ classId: e.target.value }, () => {
										this.viewPage();
									});
								}}>
									<option value="all">All Classes</option>
									{ classes.map((item, index) => (
										<option key={item._id} value={item._id}>{item.name}</option>
									)) }
								</select>
								<select className="subjects" onChange={(e) => {
									this.setState({ subjectId: e.target.value }, () => {
										this.viewPage();
									});
								}}>
									<option value="all">All Subjects</option>
									{ subjects.map((item, index) => (
										<option key={item._id} value={item._id}>{item.name}</option>
									)) }
								</select>
								<div className="search clearfix">
									<input type="text" name="search-input" id="search-input" placeholder="Enter keyword..." onKeyDown={(e) => {
										if(e.keyCode === 13) {
											this.setState({ keyword: e.target.value }, () => {
												this.viewPage();
											});
										}
									}} />
									<button onClick={this.viewPage}>Search</button>
								</div>
							</div>

							<div className="pagination clearfix">
								<span>View: </span>
								<select onChange={(e) => {
									this.setState({ limit: e.target.value }, () => {
										this.viewPage();
									});
								}}>
									<option key="2" value="2">2</option>
									<option key="10" value="10">10</option>
									<option key="20" value="20">20</option>
									<option key="50" value="50">50</option>
									<option key="100" value="100">100</option>
									<option key="0" value="0">All</option>
								</select>
								<span>Page: </span>
								{ this.createPagers() }
								<span>{students.length} / {count} students</span>
							</div>
						</div>
						{/* End Toolbar */}

						{/* Students table */}
						<table>
							<thead>
								<tr>
									<th>ID.</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Email</th>
									<th>Status</th>
									<th>Last Modified</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								{ students.length > 0 && this.createTable() }
							</tbody>
						</table>
						{/* End Students table */}
					</div>

				</div>
			</Admin>
		);
	}

	createPagers() {
		const { pagers } = this.state;

		let options = [];
		for(let i = 0; i < pagers.length; i++) {
			options.push(<option key={i} value={pagers[i]}>{pagers[i]}</option>);
		}

		return <select onChange={(e) => this.viewPage(e.target.value)}>{options}</select>;
	}

	createTable() {
		let table = [];
		let students = this.state.students;
		let studentsLength = students.length;

		for(let i = 0; i < studentsLength; i++) {
			let children = [];

			children.push(<td>{students[i].student_number}</td>);
			children.push(<td>{students[i].first_name}</td>);
			children.push(<td>{students[i].last_name}</td>);
			children.push(<td>{students[i].email}</td>);
			children.push(<td><span className="status">{students[i].status}</span></td>);
			children.push(<td>{myDateFormat(students[i].date_modified)}</td>);
			children.push(<td>
				<Link to={`/admin/students/edit/${students[i]._id}`}>
					<i className="fa fa-pencil-square-o" aria-hidden="true"></i>
					Edit
				</Link>
			</td>);

			table.push(<tr key={students[i]._id}>{children}</tr>);
		}

		return table;
	}
}

export default ManageStudents;

// app/src/app/modules/Admin/ManageStudents/ManageStudents/ManageStudents.component.ts
import { Component, OnInit } from '@angular/core';

import { StudentService }    from '../ManageStudents.service';
import { ClassService }      from '../../ManageClasses/ManageClasses.service';
import { SubjectService }    from '../../ManageSubjects/ManageSubjects.service';

@Component({
	selector: 'app-manage-students',
	templateUrl: './ManageStudents.component.html',
	styleUrls: ['./ManageStudents.component.css']
})

export class ManageStudentsComponent implements OnInit {

	students  : Object[] = [];
	count     : number   = 0;
	classes   : Object[];
	subjects  : Object[];

	skip      : string = "0";
	limit     : string = "10";
	pages     : number = 0;
	pagers    : number[];
	classId   : string = 'all';
	subjectId : string = 'all';
	keyword   : string;

	constructor(
		private studentService: StudentService,
		private classService  : ClassService,
		private subjectService: SubjectService
		) {}

	ngOnInit() {
		this.getClasses();
		this.getSubjects();

		// First load
		this.getStudents();
	}

	getClasses() {
		this.classService.getAll()
			.then(resData => {
				if(resData.classes) {
					this.classes = resData.classes;
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	getSubjects() {
		this.subjectService.getAll()
			.then(resData => {
				if(resData.subjects) {
					this.subjects = resData.subjects;
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	getStudents(page: number=0) {
		// TODO: limit, skip, filter, keyword

		this.studentService.getAll({
			skip      : page,
			limit     : this.limit,
			class_id  : this.classId,
			subject_id: this.subjectId,
			keyword   : this.keyword
			})
			.then(resData => {

				// console.log("students: ", resData);

				this.students = resData.students;
				this.count    = resData.count;
				this.skip     = (Number(resData.skip) + 1).toString();
				this.limit    = resData.limit;
				this.pages    = (Number(this.limit) != 0) ? Math.ceil(Number(this.count) / Number(this.limit)) : 0;
				this.renderPagers();

			})
			.catch(err => {
				console.log(err);
			})
	}

	renderPagers() {
		this.pagers = [];
		for(let i = 1; i <= this.pages; i++){
			this.pagers.push(i);
		}
	}

	viewPage(skip: string) {
		// console.log(skip);
		let skipPage = Number(skip) > 0 ? Number(skip) - 1 : 0;

		this.getStudents(skipPage);
	}
}
<div class="page">
	<div class="head-content clearfix">
		<h1 class="title">Management Students</h1>
		<div class="action">
			<a class="button" [routerLink]="['/admin/students/create']">+ Add Student</a>
		</div>
	</div>
	<div class="body-content">

		<div class="toolbar clearfix">

			<div class="filter clearfix">
				<select class="classes" [(ngModel)]="classId" [ngModelOptions]="{standalone: true}" (change)="viewPage(0)">
					<option value="all">All Classes</option>
					<option *ngFor="let _class of classes" [value]="_class._id">{{_class.name}}</option>
				</select>
				<select class="subjects" [(ngModel)]="subjectId" [ngModelOptions]="{standalone: true}" (change)="viewPage(0)">
					<option value="all">All Subjects</option>
					<option *ngFor="let subject of subjects" [value]="subject._id">{{subject.name}}</option>
				</select>
				<div class="search clearfix">
					<!-- bo sung ngEnter sau nhe -->
					<input type="text" name="search-input" id="search-input" [(ngModel)]="keyword" placeholder="Enter keyword..." (keydown.enter)="viewPage(0)">
					<button (click)="viewPage(0)">Search</button>
				</div>
			</div>

			<div class="pagination clearfix">
				<span>View: </span>
				<select [(ngModel)]="limit" [ngModelOptions]="{standalone: true}" (change)="viewPage(0)">
					<option value="2">2</option>
					<option value="10">10</option>
					<option value="20">20</option>
					<option value="50">50</option>
					<option value="100">100</option>
					<option value="0">All</option>
				</select>
				<span>Page: </span>
				<select (change)="viewPage($event.target.value)">
					<option *ngFor="let pager of pagers" [value]="pager">{{pager}}</option>
				</select>
			</div>

		</div>

		<table>
			<tr>
				<th>ID. </th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Status</th>
				<th>Last Modified</th>
				<th>Action</th>
			</tr>
			<tr *ngFor="let item of students">
				<td>{{item.student_number}}</td>
				<td>{{item.first_name}}</td>
				<td>{{item.last_name}}</td>
				<td>{{item.email}}</td>
				<td>
					<span class="status">{{item.status}}</span>
				</td>
				<td dateFormat>{{item.date_modified}}</td>
				<td>
					<a [routerLink]="['/admin/students', 'edit', item._id]" >
						<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
						Edit
					</a>
				</td>
			</tr>
		</table>

	</div>
</div>
