// react-app/app/src/modules/Base/MyFooter/MyFooter.js
import React from 'react';

import './MyFooter.css';

class MyFooter extends React.Component {
	render() {
		return (
			<footer>
				<div className="wrapper">
					<p className="end">© 2019 By <a href="http://doanvanhuy.com" title="Doan Van Huy">Neoreul</a>. All Rights Reserved</p>
				</div>
			</footer>
		);
	}
}

export default MyFooter;

// app/src/app/modules/Base/MyFooter/MyFooter.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-footer',
	templateUrl: './MyFooter.component.html',
	styleUrls: ['./MyFooter.component.css']
})

export class MyFooterComponent {
	
}
<footer>
	<div class="wrapper">
		<p class="end">© 2019 By <a href="doanvanhuy.com" title="Doan Van Huy">Neoreul</a>. All Rights Reserved</p>
	</div>
</footer>
