// react-app/app/src/modules/Auth/Login/Login.js
import React from 'react';

import '../SignUp/SignUp.css';
import avatar from '../../../assets/images/avatar.png';

import LoginSuccess from './LoginSuccess';
import LoginForm from './LoginForm';

import { checkLogin } from '../Auth.services';

class Login extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			isLoggedIn: false,
			message: ""
		};
	}

	componentDidMount() {
		this.checkLogin();
	}

	checkLogin() {
		// Check service here
		this.setState({ isLoggedIn: checkLogin() }, () => {
			this.setMessage();
		});
	}

	loginSubmit(value) {

		// console.log("login submit: ", value);

		this.setState({ isLoggedIn: value }, () => {
			this.setMessage();

			if(value) {
				setTimeout(() => {
					this.props.history.push('/admin/dashboard');
				}, 1500);
			}
		});
	}

	logoutSubmit() {
		// TODO: call service logout here
		this.setState({ isLoggedIn: false });

		this.setMessage();
	}

	setMessage() {
		this.setState({ message: 'Logged ' + (this.state.isLoggedIn ? 'in!' : 'out!') });
	}

	render() {
		const isLoggedIn = this.state.isLoggedIn;
		let renderContent;

		if(isLoggedIn) {
			renderContent = <LoginSuccess message={this.state.message} submit={() => this.logoutSubmit()} />;
		} else {
			renderContent = <LoginForm submit={(isLoggedIn) => this.loginSubmit(isLoggedIn)}/>;
		}

		return (
			<div className="login-signup">
				<div className="head-content clearfix">
					<div className="feature-img">
						<img src={ avatar } title="My Courses" alt="My Courses"/>
					</div>
					<h1 className="title">Login</h1>
				</div>
				<div className="body-content">
					{renderContent}
				</div>
			</div>
		);
	}
}

export default Login;

// app/src/app/modules/Auth/Login/Login.component.ts
import { Component } from '@angular/core';
import { NavigationExtras, Router } from '@angular/router';

import { AuthService } from '../Auth.services';
import { CookieService } from '../../Base/Cookie/cookie.service';

import { AppConfig } from '../../../config/index';

import { Observable } from 'rxjs';

@Component({
	selector: 'app-login',
	templateUrl: './Login.component.html',
	styleUrls: ['../../SignUp/SignUp.component.css', './Login.component.css']
})

export class LoginComponent { 
	isLogged : boolean;
	isError  : boolean = false;
	notify   : string;
	message  : string;

	constructor(
		private authService: AuthService,
		private cookieService: CookieService,
		private router: Router) {
		// this.setMessage();
		this.checkLogin();
	}

	setMessage() {
		// console.log(this.authService.isLoggedIn);
		this.message = 'Logged ' + (this.isLogged ? 'in!' : 'out!');
	}

	checkLogin() {
		this.isLogged = (this.cookieService.get(AppConfig.COOKIE_VALUE.SESSIONID) != "") ? true : false;

		if(this.isLogged) {
			// this.router.navigate(['admin/dashboard']);
			this.setMessage();
		}
	}

	login(userData: any) {
		this.message = "Trying to log in...";
		this.isError = false;
		this.notify  = "";

		this.authService
			.login(userData)
			.then(resData => {
				// console.log("#Client.userLogin: ", resData);

				this.setMessage();

				// console.log(this.authService.isLoggedIn);

				if(this.authService.isLoggedIn) {

					let redirect = this.authService.redirectUrl ? this.router.parseUrl(this.authService.redirectUrl) : 'admin/dashboard';

					// let navigationExtras: NavigationExtras = {
					// 	queryParamsHandling: 'preserve',
					// 	preserveFragment   : true
					// };

					setTimeout(() => {
						this.router.navigate([redirect]);
					}, 1500);
				}

				if(resData.err && resData.err === 1) {
					this.isError = true;
					this.notify = resData.msg;
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	logout() {
		this.authService.logout();
		this.setMessage();
	}
}
<div class="login-signup">
	<div class="head-content clearfix">
		<div class="feature-img">
			<img src="app/assets/images/avatar.png" title="My Courses">
		</div>
		<h1 class="title">Login</h1>
	</div>
	<div class="body-content">

		<form *ngIf="!isLogged" #loginForm = "ngForm" (ngSubmit)="login(loginForm.value)">
			
			<div class="notify" [ngClass]="{ 'active': isError }">{{notify}}</div>

			<div class="input">
				<label for="username">
					Username
					<span class="required">*</span>
				</label>
				<input type="text" id="username" name="username" ngModel>
			</div>

			<div class="input">
				<label for="password">
					Password
					<span class="required">*</span>
				</label>
				<input type="password" id="password" name="password" ngModel>
			</div>

			<div class="action">
				<button class="button" type="submit">Login</button>
				<p>
					<span>Don't have an account? </span>
					<a [routerLink]="['/sign-up']">Sign Up now!</a>	
				</p>
			</div>
		</form>

		<div *ngIf="isLogged">
			<p class="link">{{message}}</p>
			<br>
			<button class="button" (click)="logout()">Logout</button>
		</div>
	</div>
</div>
