// app/src/app/modules/Base/MyHeader/MyHeader.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-header',
	templateUrl: './MyHeader.component.html',
	styleUrls: ['./MyHeader.component.css']
})

export class MyHeaderComponent {
	
}
<header class="clearfix">
	<!-- <div class="wrapper"> -->
		<div class="logo">
			<a href="/">
				<!-- <img src=""> -->
				<h3>My Courses</h3>
			</a>
		</div>
		<app-menu></app-menu>
	<!-- </div> -->
</header>

// react-app/app/src/modules/Base/MyHeader/MyHeader.js
import React from 'react';

import './MyHeader.css';

import Menu from '../Menu/Menu';

class MyHeader extends React.Component {
	render() {
		return (
			<header className="clearfix">
				<div className="logo">
					<a href="/">
						<h3>My Courses</h3>
					</a>
				</div>
				<Menu />
			</header>
		);
	}
}

export default MyHeader;
