// react-app/app/src/modules/Admin/ManageTeachers/ModifyTeacher/ModifyTeacher.js
import React from 'react';

import { getTeacher, removeTeacher, createOrModifyTeacher } from '../ManageTeachers.services';
import { getSubjects } from '../../ManageSubjects/ManageSubjects.services';

import Admin from '../../Admin';

import { Teacher } from './Teacher';

class ModifyTeacher extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			title    : "",
			teacherId  : "",
			teacherItem: Teacher,
			isError  : false,
			notify   : "",
			isDone   : false,
			tab      : 'general',
			subjects : []
		};

		this.createOrModify = this.createOrModify.bind(this);
		this.delete = this.delete.bind(this);
	}

	componentDidMount() {
		this.checkMode();
	}

	changeTab(tab) {
		this.setState({ tab });
	}

	getSubjects() {
		getSubjects()
			.then(res => {
				let subjects = res.data.subjects;

				if(this.state.teacherId) {
					subjects.forEach(s => {
						s["checked"] = false;

						for(let i = 0; i < this.state.teacherItem["subjects"].length; i++) {
							if(this.state.teacherItem["subjects"][i] === s["_id"]) {
								s["checked"] = true;
							}
						}
					});

					this.setState({ subjects });
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	checkMode() {
		let teacherId = this.props.match.params.id;

		if(teacherId && !isNaN(Number(teacherId))) {
			this.setState({
				title: 'Edit Teacher',
				teacherId
			}, () => {
				this.getTeacher();
			});
		} else {
			this.setState({
				teacherItem: Teacher,
				title: 'Create Teacher'
			});
		}
	}

	getTeacher() {
		const { teacherId } = this.state;

		getTeacher(Number(teacherId))
			.then(res => {
				this.setState({ teacherItem: res.data }, () => {
					this.getSubjects();
				});
			})
			.catch(err => {
				console.log(err);
			});
	}

	createOrModify(isContinue=false) {
		this.setState({
			notify: "",
			isError: false,
			isDone: false
		});

		const { teacherItem } = this.state;

		teacherItem["subjects"] = [];
		this.state.subjects.forEach(s => {
			if(s["checked"] === true) {
				teacherItem["subjects"].push(s["_id"]);
			}
		});

		createOrModifyTeacher(teacherItem)
			.then(res => {
				let resData = res.data;
				if(resData.ok && resData.ok === 1) {
					this.setState({ isDone: true });

					if(!isContinue) {
						this.setState({ teacherItem: Teacher }, () => {
							this.props.history.push("/admin/teachers");
						});
					} else {
						this.setState({ teacherItem });
					}
				}

				if(resData.err && resData.err === 1) {
					this.setState({
						notify: resData.msg,
						isError: true
					});
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	delete() {
		let isConfirm = window.confirm("Are you sure delete this teacher?");
		if(isConfirm) {
			const { teacherId } = this.state;
			removeTeacher(Number(teacherId))
				.then(res => {
					this.props.history.push('/admin/teachers');
				})
				.catch(err => {
					console.log(err);
				});
		}
	}

	render() {
		const { title, teacherId, teacherItem, isError, notify, isDone, subjects, tab } = this.state;

		let deleteBtn;
		if(teacherId) {
			deleteBtn = <a className="button" onClick={this.delete}>Delete</a>;
		} else {
			deleteBtn = null;
		}

		return (
			<Admin>
				<div className="page">
					<div className="head-content clearfix">
						<h1 className="title">{title}</h1>

						<div className="action">
							{ deleteBtn }
							<a className="button" onClick={() => this.createOrModify()}>Save</a>
							<a className="button" onClick={() => this.createOrModify(true)}>Save And Continue</a>
						</div>
					</div>
					<div className="body-content">
						<form>
							<div className={"notify " + (isError? 'active' : '')}>{notify}</div>
							<div className={"notify success " + (isDone? 'active' : '')}>Saved!</div>

							<ul className="tabs clearfix">
								<li className={tab === 'general' ? 'active': ''} onClick={() => this.changeTab('general')}>General</li>
								<li className={tab === 'address' ? 'active': ''} onClick={() => this.changeTab('address')}>Address</li>
								<li className={tab === 'subjects' ? 'active': ''} onClick={() => this.changeTab('subjects')}>Subjects</li>

							</ul>

							<div className={'tab-content ' + (tab === 'general'? 'show': '')}>

								<div className="input">
									<label htmlFor="teacher_number">
										Teacher Number
										<span className="required">*</span>
									</label>
									<input type="text" id="teacher_number" name="teacher_number" value={teacherItem.teacher_number} onChange={(e) => this.onChangeTeacherItem("teacher_number", e.target.value)} />
								</div>

								<div className="col2">

									<div className="input">
										<label htmlFor="first_name">
											First Name
											<span className="required">*</span>
										</label>
										<input type="text" id="first_name" name="first_name" value={teacherItem.first_name} onChange={(e) => this.onChangeTeacherItem("first_name", e.target.value)} />
									</div>

									<div className="input">
										<label htmlFor="last_name">
											Last Name
											<span className="required">*</span>
										</label>
										<input type="text" id="last_name" name="last_name" value={teacherItem.last_name} onChange={(e) => this.onChangeTeacherItem("last_name", e.target.value)} />
									</div>									

								</div>

								<div className="col2">

									<div className="input">
										<label htmlFor="email">
											Email
											<span className="required">*</span>
										</label>
										<input type="text" id="email" name="email" value={teacherItem.email} onChange={(e) => this.onChangeTeacherItem("email", e.target.value)} />
									</div>

									<div className="input">
										<label htmlFor="age">
											Age
										</label>
										<select onChange={(e) => {this.onChangeTeacherItem('age', e.target.value)}}>
											<option value=""></option>
											<option value="23">23</option>
											<option value="24">24</option>
											<option value="25">25</option>
											<option value="26">26</option>
											<option value="27">27</option>
											<option value="28">28</option>
											<option value="29">29</option>
											<option value="30">30</option>
											<option value="31">31</option>
											<option value="32">32</option>
											<option value="33">33</option>
											<option value="34">34</option>
											<option value="35">35</option>
										</select>
									</div>

								</div>

								<div className="col2">

									<div className="input">
										<label htmlFor="faculty">
											Faculty
										</label>
										<select value={teacherItem.faculty} onChange={(e) => this.onChangeTeacherItem("faculty", e.target.value)}>
											<option value="it">Information Teachnology</option>
											<option value="ms">Mathematics and Statistics</option>
										</select>
									</div>

									<div className="input">
										<label htmlFor="marjor">
											Marjor
										</label>
										<select value={teacherItem.marjor} onChange={(e) => this.onChangeTeacherItem("marjor", e.target.value)}>
											<option value="knpm">Software Engineer</option>
										</select>
									</div>

								</div>

								<div className="input">
									<label htmlFor="status">
										Status
										<span className="required">*</span>
									</label>
									<select onChange={(e) => this.onChangeTeacherItem("status", e.target.value)}>
										<option value="teaching">Teaching</option>
										<option value="leaved">Leaved</option>
									</select>
								</div>

							</div>

							<div className={'tab-content ' + (tab === 'address'? 'show': '')}>

								<div className="input">
									<label htmlFor="special_name">
										Special Name
									</label>
									<input type="text" id="special_name" name="special_name" value={teacherItem.special_name} onChange={(e) => this.onChangeTeacherItem("special_name", e.target.value)} />
								</div>

								<div className="input">
									<label htmlFor="street_address1">
										Street Address
									</label>
									<input type="text" id="street_address1" name="street_address1" value={teacherItem.street_address1} onChange={(e) => this.onChangeTeacherItem("street_address1", e.target.value)} />
								</div>

								<div className="input">
									<label htmlFor="street_address2">
										Apartment, Floor, etc.
									</label>
									<input type="text" id="street_address2" name="street_address2" value={teacherItem.street_address2} onChange={(e) => this.onChangeTeacherItem("street_address2", e.target.value)} />
								</div>

								<div className="col2">

									<div className="input">
										<label htmlFor="city">
											City
										</label>
										<input type="text" id="city" name="city" value={teacherItem.city} onChange={(e) => this.onChangeTeacherItem("city", e.target.value)} />
									</div>

									<div className="input">
										<label htmlFor="state">
											State
										</label>
										<select onChange={(e) => {this.onChangeTeacherItem('state', e.target.value)}}>
											<option value="AL">Alabama</option>
											<option value="AK">Alaska</option>
											<option value="CA">California</option>
											<option value="FL">Florida</option>
											<option value="HI">Hawaii</option>
											<option value="IN">Indiana</option>
											<option value="KY">Kentucky</option>
											<option value="MI">Michigan</option>
											<option value="NV">Nevada</option>
											<option value="OH">Ohio</option>
										</select>
									</div>

								</div>

								<div className="col2">

									<div className="input">
										<label htmlFor="zipcode">
											Zipcode
										</label>
										<input type="text" id="zipcode" name="zipcode" value={teacherItem.zipcode} onChange={(e) => this.onChangeTeacherItem("zipcode", e.target.value)} />
									</div>

									<div className="input">
										<label htmlFor="phone">
											Phone
										</label>
										<input type="text" id="phone" name="phone" value={teacherItem.phoney} onChange={(e) => this.onChangeTeacherItem("phone", e.target.value)} />
									</div>

								</div>

							</div>

							<div className={'tab-content ' + (tab === 'subjects'? 'show': '')}>

								<ul className="list-checkbox">

									{ subjects.map((item, index) => (
										<li key={index}>
											<label className="container">{item.name}
												<input type="checkbox" name={item._id} defaultChecked={item.checked} onChange={() => this.onChangeSubjects(item, index)} />
												<span className="checkmark"></span>
											</label>
										</li>
									)) }

								</ul>

							</div>

						</form>
					</div>
				</div>
			</Admin>
		);
	}

	onChangeTeacherItem(key, value) {
		this.setState(prevState => {
			let teacherItem = {...prevState.teacherItem};

			teacherItem[key] = value;

			return {
				teacherItem
			};
		});
	}

	onChangeSubjects(item, index) {

		this.setState((prevState) => {
			let subjects = [...prevState.subjects];

			item["checked"] = !item["checked"];

			subjects[index] = item;

			return {
				subjects
			};
		});
	}
}

export default ModifyTeacher;

// app/src/app/modules/Admin/ManageTeachers/ModifyTeacher/ModifyTeacher.component.ts
import { Component, OnInit, OnChanges } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

import { TeacherService } from '../ManageTeachers.service';
import { SubjectService } from '../../ManageSubjects/ManageSubjects.service';

@Component({
	selector: 'modify-teacher',
	templateUrl: './ModifyTeacher.component.html',
	styleUrls: ['./ModifyTeacher.component.css']
})

export class ModifyTeacherComponent implements OnInit, OnChanges {
	title    : string;
	teacherId  : string;
	teacherItem: Object = {};
	isError  : boolean = false;
	notify   : string;
	isDone   : boolean = false;
	tab      : string = 'general';
	subjects : Object[];

	constructor(
		private teacherService: TeacherService,
		private activatedRoute: ActivatedRoute,
		private subjectService: SubjectService,
		private router: Router) {
	}

	ngOnInit() {
		this.checkMode();
	}

	ngOnChanges() {
		this.checkMode();
	}

	changeTab(tab: string='general') {
		this.tab = tab;
	}

	checkMode() {
		this.teacherId = this.activatedRoute.snapshot.paramMap.get('id');
		// console.log(this.teacherId);

		if(this.teacherId && !isNaN(Number(this.teacherId))) {
			this.title = "Edit Teacher";
			this.getTeacher();
		} else {
			this.teacherItem = {};
			this.title = "Create Teacher";
			this.getSubjects();
		}
	}

	getTeacher() {
		this.teacherService.get(Number(this.teacherId))
			.then(resData => {
				// console.log("teacher: ", resData);
				if(resData) {
					this.teacherItem = resData;

					this.getSubjects();
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	getSubjects() {
		this.subjectService.getAll()
			.then(resData => {
				// console.log(resData);

				if(resData.subjects) {
					this.subjects = resData.subjects;

					if(this.teacherId) {

						this.subjects.forEach(s => {
							s["checked"] = false;

							for(let i = 0; i < this.teacherItem["subjects"].length; i++) {
								if(this.teacherItem["subjects"][i] === s["_id"]) {
									s["checked"] = true;
								}
							}
						});

					}
				}
			})
			.catch(err => {
				console.log(err);
			});
	}

	createOrModify(isContinue: boolean=false) {
		this.notify = "";
		this.isError= false;
		this.isDone = false;

		this.teacherItem["subjects"] = [];
		this.subjects.forEach(s => {
			if(s["checked"] == true) {
				this.teacherItem["subjects"].push(s["_id"]);
			}
		});

		// console.log(this.teacherItem);

		this.teacherService.createOrModify(this.teacherItem)
			.then(resData => {
				// console.log("create or modify teacher: ", resData);

				if(resData.ok && resData.ok === 1) {
					this.isDone = true;
					if(!isContinue) {
						this.teacherItem = {};
						this.router.navigate(['admin/teachers']);
					}
				}

				if(resData.err && resData.err === 1) {
					this.notify = resData.msg;
					this.isError= true;
				}

			})
			.catch(err => {
				console.log(err);
			});
	}

	delete() {
		let isConfirm = confirm("Are you sure delete this teacher?");
        if(isConfirm){
            this.teacherService.remove(Number(this.teacherId))
            	.then(resData => {
            		// console.log(resData);
            		this.router.navigate(['admin/teachers']);
            	})
            	.catch(err => {
            		console.log(err);
            	});
        }
	}
}
<div class="page">
	<div class="head-content clearfix">
		<h1 class="title">{{title}}</h1>

		<div class="action">
			<a class="button" *ngIf="teacherId" (click)="delete()">Delete</a>
			<a class="button" (click)="createOrModify()">Save</a>
			<a class="button" (click)="createOrModify(true)">Save And Continue</a>
		</div>
	</div>
	<div class="body-content">

		<form>
			
			<div class="notify" [ngClass]="{ 'active': isError }">{{notify}}</div>
			<div class="notify success" [ngClass]="{'active': isDone}">Saved!</div>

			<ul class="tabs clearfix">
				<li [ngClass]="{'active': tab === 'general'}" (click)="changeTab('general')">General</li>
				<li [ngClass]="{'active': tab === 'address'}" (click)="changeTab('address')">Address</li>
				<li [ngClass]="{'active': tab === 'subjects'}" (click)="changeTab('subjects')">Subjects</li>
			</ul>

			<div class="tab-content" [ngClass]="{'show': tab === 'general'}">

				<div class="input">
					<label for="teacher_number">
						Teacher Number
						<span class="required">*</span>
					</label>
					<input type="text" id="teacher_number" name="teacher_number" [(ngModel)]="teacherItem.teacher_number">
				</div>

				<div class="col2">

					<div class="input">
						<label for="first_name">
							First Name
							<span class="required">*</span>
						</label>
						<input type="text" id="first_name" name="first_name" [(ngModel)]="teacherItem.first_name">
					</div>

					<div class="input">
						<label for="last_name">
							Last Name
							<span class="required">*</span>
						</label>
						<input type="text" id="last_name" name="last_name" [(ngModel)]="teacherItem.last_name">
					</div>

				</div>

				<div class="col2">
					<div class="input">
						<label for="email">
							Email
							<span class="required">*</span>
						</label>
						<input type="text" id="email" name="email" [(ngModel)]="teacherItem.email">
					</div>

					<div class="input">
						<label for="age">
							Age
						</label>
						<select [(ngModel)]="teacherItem.age" [ngModelOptions]="{standalone: true}">
							<option value="23">23</option>
							<option value="24">24</option>
							<option value="25">25</option>
							<option value="26">26</option>
							<option value="27">27</option>
							<option value="28">28</option>
							<option value="29">29</option>
							<option value="30">30</option>
							<option value="31">31</option>
							<option value="32">32</option>
							<option value="33">33</option>
							<option value="34">34</option>
							<option value="35">35</option>
						</select>
					</div>
				</div>

				<div class="col2">
					<div class="input">
						<label for="faculty">
							Faculty
						</label>
						<select [(ngModel)]="teacherItem.faculty" [ngModelOptions]="{standalone: true}">
							<option value="it">Information Teachnology</option>
							<option value="ms">Mathematics and Statistics</option>
						</select>
					</div>
					<div class="input">
						<label for="marjor">
							Marjor
						</label>
						<select [(ngModel)]="teacherItem.marjor" [ngModelOptions]="{standalone: true}">
							<option value="knpm">Software Engineer</option>
						</select>
					</div>
				</div>

				<div class="input">
					<label for="status">
						Status
						<span class="required">*</span>
					</label>
					<select [(ngModel)]="teacherItem.status" [ngModelOptions]="{standalone: true}">
						<option value="teaching">Teaching</option>
						<option value="leaved">Leaved</option>
					</select>
				</div>

			</div>


			<div class="tab-content" [ngClass]="{'show': tab === 'address'}">
				
				<div class="input">
					<label for="special_name">
						Special Name
					</label>
					<input type="text" id="special_name" name="special_name" [(ngModel)]="teacherItem.special_name">
				</div>

				<div class="input">
					<label for="street_address1">
						Street Address
					</label>
					<input type="text" id="street_address1" name="street_address1" [(ngModel)]="teacherItem.street_address1">
				</div>

				<div class="input">
					<label for="street_address2">
						Apartment, Floor, etc.
					</label>
					<input type="text" id="street_address2" name="street_address2" [(ngModel)]="teacherItem.street_address2">
				</div>

				<div class="col2">

					<div class="input">
						<label for="city">
							City
						</label>
						<input type="text" id="city" name="city" [(ngModel)]="teacherItem.city">
					</div>

					<div class="input">
						<label for="state">
							State
						</label>
						<select [(ngModel)]="teacherItem.state" [ngModelOptions]="{standalone: true}">
							<option value="AL">Alabama</option>
							<option value="AK">Alaska</option>
							<option value="CA">California</option>
							<option value="FL">Florida</option>
							<option value="HI">Hawaii</option>
							<option value="IN">Indiana</option>
							<option value="KY">Kentucky</option>
							<option value="MI">Michigan</option>
							<option value="NV">Nevada</option>
							<option value="OH">Ohio</option>
						</select>
					</div>

				</div>

				<div class="col2">

					<div class="input">
						<label for="zipcode">
							Zipcode
						</label>
						<input type="text" id="zipcode" name="zipcode" [(ngModel)]="teacherItem.zipcode">
					</div>
					<div class="input">
						<label for="phone">
							Phone
						</label>
						<input type="text" id="phone" name="phone" [(ngModel)]="teacherItem.phone">
					</div>
				</div>

			</div>

			<div class="tab-content" [ngClass]="{'show': tab === 'subjects'}">
				
				<!-- Move to Directive ListCheckbox -->
				<ul class="list-checkbox">
					<li *ngFor="let subject of subjects">
						<label class="container">{{subject.name}}
							<input type="checkbox" [name]="subject._id" [(ngModel)]="subject.checked" value="subject._id">
							<span class="checkmark"></span>
						</label>
					</li>
				</ul>
				
			</div>

		</form>
	</div>
</div>
